[phases.setup]
onlyIncludeFiles = []
nixPkgs = ['nodejs_22', 'pnpm_9', 'openssl', 'caddy']

[phases.install]
cmds = ['pnpm install']

[phases.build]
cmds = ['npm install && npm run build']

[phases.start]
cmd = 'node dist/server.js'
