[build]
# builder = "NIXPACKS"

[deploy]
startCommand = "sh -c 'echo \"Starting Node...\"; node dist/server.js & echo \"Node PID $!\"; sleep 5; echo \"Starting Caddy...\"; caddy run --config /etc/caddy/Caddyfile --adapter caddyfile'"
